// <auto-generated />
namespace DancingSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dodanie_Roli : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodanie_Roli));
        
        string IMigrationMetadata.Id
        {
            get { return "202106251223106_Dodanie_Roli"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
